#!/bin/bash
i=$(echo "$@"); z=0; while [ $z != $(echo $i|wc -m) ]; do i=$(y=$(cat /dev/urandom | tr -dc 'a-z0-9' | fold -w 1 | head -n 1);echo $i|sed s/./$y/$(shuf -i 1-$(echo $i|wc -m) -n 1));echo $i; z=$(($z+1)); done

